### ISSUE TITLE
現存のバグ・未実装問題リスト

### ISSUE THREAD

**Issue by rikuto1231** [HRK-EXEX/DenGonChiZu#2]
- [x] G1-1:addbuttonのpng背景が透過されない
- [x] G1-1:クリック時の相対座標の計算と取得

**Comment by HRK-EXEX** [comment]
- [ ] 全般：POSTデータが画面遷移時に保持されない

**Comment by rikuto1231** [comment]
- [ ] 拡大・縮小実装に伴うside.phpでのボタンのCSSレイアウト

**Comment by rikuto1231** [comment]
- [ ] G1-1表示部分の背景UIを親しみもてる背景にする
